language: julia
codecov: true
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.4
if: branch = master OR tag IS present OR type = pull_request
notifications:
  email: false
jobs:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
